global:
  scrape_interval: 15s # default is 15s
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'
  
scrape_configs:
  - job_name: 'prom'
    scrape_interval: 5s # override the global 
    static_configs:
      - targets: ['localhost:9090']