apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: saurabh3460@gmail.com.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
       ingress:
         class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-ccx
  namespace: mon
spec:
  dnsNames:
  - grafana.saurabhdev.in
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: grafana-certs