apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  serviceAccountName: ecr
  containers:
  - name: test
    image: docker
    command: [ "docker", "pull", "824614981818.dkr.ecr.ap-south-1.amazonaws.com/nimble:latest" ]
    