# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_NAME = "bento/ubuntu-18.04"
NODES = 1

IMAGE_NAME = "bento/ubuntu-18.04"

ANSIBLE_NODES = 0


Vagrant.configure("2") do |config|

    (0...NODES).each do |i|
        config.vm.define "ansible-node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 20}"
            node.vm.hostname = "ansible-node-#{i}"

            # naming the virtualmachine
            node.vm.provider :virtualbox do |vb|
                vb.name = "ansible-node-#{i}"
                vb.memory = 1000
            end
            
            # execute nodes-sshd.sh for configuring ssh.
            # node.vm.provision :shell, path: "files/nodes-sshd.sh"

            #node.vm.provision "ansible" do |ansible|
            #    ansible.compatibility_mode = "2.0"
            #    ansible.playbook = "ansible-node-config.yml"
            #    ansible.extra_vars = {
            #        node_ip: "192.168.50.#{i + 20}",
            #    }
            #end
        end
    end


end
