version: '3.2'
services: 
  prom-pushgateway:
    image: bitnami/pushgateway
    ports: 
      - 9091:9091
  prometheus:
    image: bitnami/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    # network_mode: host
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana

volumes:
  prometheus-data: {}
  grafana-data: {}


  # app1:
  #   image: app:0.1
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - APP_PUSH_GATEWAY=http://prom-pushgateway:9091
  # app2:
  #   image: app:0.1
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     - APP_PUSH_GATEWAY=http://prom-pushgateway:9091