global:
  scrape_interval:     15s
  # The evaluation_interval option controls how often Prometheus will evaluate rules. 
  # Prometheus uses rules to create new time series and to generate alerts.
  evaluation_interval: 15s

# The rule_files block specifies the location of any rules we want the Prometheus server to load
rule_files:
  # - "first.rules"
  # - "second.rules"


# controls what resources Prometheus monitors.
scrape_configs:
  - job_name: prometheus  
    static_configs:
      - targets: ['localhost:9090']

  - job_name: pushgateway
    # metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['prom-pushgateway:9091']
        labels:
          service: 'pushgateway'


