- name: install unzip
  package:
    name: unzip
    state: latest
- name: intsall terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.14.8/terraform_0.14.8_openbsd_amd64.zip
    dest: /user/local/bin
    remote_src: yes
    owner: root
    group: root
    mode: 0755
