---
- name: Set up nginx 
  hosts: web 
  become: true
  tasks:
    - name: update 
      apt: 
        update_cache: yes
    - name: Install apache
      apt:
        name: apache2
        state: absent
