apiVersion: v1
kind: ConfigMap
metadata:
  name: rule-engine-config
data: 
  config.yaml: | 
    port: {{ .Values.app.port }}
    hosts:
    {{- toYaml .Values.app.hosts | nindent 4 }}
    archive_locations:
    {{- toYaml .Values.app.archive_locations | nindent 4 }} 



