- name: Create monitor group
  group:
    name: monitor
    state: present

- name: Create monitor user
  user:
    name: monitor
    group: monitor
    createhome: no
    system: yes
    state: present

- name: Create /opt/prometheus
  file:
    name: /opt/prometheus
    state: directory

- name: Download node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{node_exporter_version}}/node_exporter-{{node_exporter_version}}.linux-amd64.tar.gz
    dest: /opt/prometheus

- name: Unarchive node_exporter
  unarchive:
    remote_src: yes
    src: /opt/prometheus/node_exporter-{{node_exporter_version}}.linux-amd64.tar.gz
    dest: /opt/prometheus

- name: Create symlink to node_exporter
  file:
    src: /opt/prometheus/node_exporter-{{node_exporter_version}}.linux-amd64/node_exporter
    path: /usr/bin/node_exporter
    state: link

- name: install unit file to systemd
  template:
    src: /template/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: configure systemd to use service
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: node_exporter.service

- name: restart node_exporter
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: node_exporter.service
    # https://www.golinuxcloud.com/ansible-roles-directory-structure-tutorial/
    # https://www.golinuxcloud.com/jinja2-template/
