---
- hosts: all
  become: true
  tasks:
    - name: update repo index
      apt:
        update_cache: yes

    - name: install apache2 package
      apt:
        name: apache2
        state: absent # this state is to remove the package

    - name: add php support for apache
      apt:
        name: libapache2-mod-php
        state: absent # this state is to remove the package

