---
- hosts: all
  become: true
  pre_tasks:
    - name: Update the CentOS
      dnf:
        update_only: true
        update_cache: true
      when: ansible_distribution == "CentOS"
      tags: always

    - name: Update the Ubuntu
      apt:
        upgrade: dist
        update_cache: true
      when: ansible_distribution in ["Debian", "Ubuntu"]
      tags: always

- hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers

- hosts: workstation
  become: true
  roles:
    - workstation
