# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
  
    # Customize the amount of memory on the VM:
    vb.memory = "1000"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  (1..2).each do |i|
  	config.vm.define "nomad-a-#{i}" do |n|
  	if i == 1
  		n.vm.network "forwarded_port", guest: 4646, host: 4646, auto_correct: true
  	end
  	n.vm.hostname = "nomad-a#{i}"
  	n.vm.network "private_network", ip: "172.16.1.#{i+100}"
  end
end
